// Grid dimensions for pixel powder simulation
export const GRID_WIDTH = 240;
export const GRID_HEIGHT = 160;
export const CELL_SIZE = 4; // Canvas size: 960x640

// Particle Type IDs
export const ELEMENT = {
  EMPTY: 0,
  BOTTLE: 1,         // Glass container boundary (indestructible)
  RAMP_LEFT: 2,      // Ramps down to left
  RAMP_RIGHT: 3,     // Ramps down to right
  SAND_GOLD: 4,      // Sunset Gold Sand (heavy, falls)
  ANTI_GRAV: 5,      // Anti-Grav Teal Sand (floats up)
  LASER_SAND: 6,     // Laser Sand (emits directional beams)
  ANTI_MATTER: 7,    // Anti-Matter Void Sand (annihilates barriers)
  PORTAL_A: 8,       // Blue portal entrance/exit
  PORTAL_B: 9,       // Orange portal entrance/exit
  ELECTRICITY: 10,   // Electric spark / current
  CONDUCTOR: 11,     // Wire/Metal that conducts electricity
  MAGNETITE: 12,     // Magnetic field generator particle
  SAND_BLUE: 13,     // Ocean Blue Sand
  SAND_PINK: 14,     // Neon Pink Sand
  SAND_GREEN: 15,    // Emerald Green Sand
  LAVA: 16,          // Lava Sand (glowing hot hazard)
  LASER_BEAM_L: 17,  // Energy beam particle moving left
  STEAM: 18,         // Steam gas generated by heat/reaction
  LASER_BEAM_R: 19,  // Energy beam particle moving right
  LASER_BEAM_U: 20,  // Energy beam particle moving up
  LASER_BEAM_D: 21,  // Energy beam particle moving down
  ACID: 22,          // Corrosive Acid Sand
};

// Colors for Retro Pixel Rendering (8-bit / 16-bit Palette)
export const ELEMENT_COLORS = {
  [ELEMENT.EMPTY]: '#0a0a12',
  [ELEMENT.BOTTLE]: '#4a6288',
  [ELEMENT.RAMP_LEFT]: '#8a9bb8',
  [ELEMENT.RAMP_RIGHT]: '#8a9bb8',
  [ELEMENT.SAND_GOLD]: '#f0c040',
  [ELEMENT.SAND_BLUE]: '#00bfff',
  [ELEMENT.SAND_PINK]: '#ff00aa',
  [ELEMENT.SAND_GREEN]: '#00ff66',
  [ELEMENT.ANTI_GRAV]: '#30e0e0',
  [ELEMENT.LASER_SAND]: '#ff3366',
  [ELEMENT.ANTI_MATTER]: '#a020f0',
  [ELEMENT.PORTAL_A]: '#00bfff',
  [ELEMENT.PORTAL_B]: '#ff8c00',
  [ELEMENT.ELECTRICITY]: '#ffff33',
  [ELEMENT.CONDUCTOR]: '#708090',
  [ELEMENT.MAGNETITE]: '#9400d3',
  [ELEMENT.LAVA]: '#ff4400',
  [ELEMENT.ACID]: '#33ff33',
  [ELEMENT.LASER_BEAM_L]: '#ff5588',
  [ELEMENT.LASER_BEAM_R]: '#ff5588',
  [ELEMENT.LASER_BEAM_U]: '#ff5588',
  [ELEMENT.LASER_BEAM_D]: '#ff5588',
  [ELEMENT.STEAM]: '#aaaaaa88',
};

// Active/Glow colors for UI and powered states
export const ELEMENT_GLOW = {
  [ELEMENT.SAND_GOLD]: 'rgba(240, 192, 64, 0.3)',
  [ELEMENT.SAND_BLUE]: 'rgba(0, 191, 255, 0.4)',
  [ELEMENT.SAND_PINK]: 'rgba(255, 0, 170, 0.4)',
  [ELEMENT.SAND_GREEN]: 'rgba(0, 255, 102, 0.4)',
  [ELEMENT.ANTI_GRAV]: 'rgba(48, 224, 224, 0.5)',
  [ELEMENT.LASER_SAND]: 'rgba(255, 51, 102, 0.6)',
  [ELEMENT.ANTI_MATTER]: 'rgba(160, 32, 240, 0.6)',
  [ELEMENT.ELECTRICITY]: 'rgba(255, 255, 51, 0.8)',
  [ELEMENT.LAVA]: 'rgba(255, 68, 0, 0.7)',
  [ELEMENT.ACID]: 'rgba(51, 255, 51, 0.6)',
};

// UI Info for Sand Stream Palette
export const ELEMENT_INFO = {
  [ELEMENT.SAND_GOLD]: {
    name: 'Sunset Gold Sand',
    key: '1',
    icon: '⏳',
    desc: 'Golden sand stream that cascades and stacks under gravity.',
    category: 'sand'
  },
  [ELEMENT.SAND_BLUE]: {
    name: 'Ocean Blue Sand',
    key: '2',
    icon: '🌊',
    desc: 'Vibrant blue sand stream for creating rich color layers.',
    category: 'sand'
  },
  [ELEMENT.SAND_PINK]: {
    name: 'Neon Pink Sand',
    key: '3',
    icon: '🌸',
    desc: 'Bright magenta sand stream for beautiful sand art contrast.',
    category: 'sand'
  },
  [ELEMENT.SAND_GREEN]: {
    name: 'Emerald Green Sand',
    key: '4',
    icon: '🌿',
    desc: 'Lush green sand stream for colorful bottle stratification.',
    category: 'sand'
  },
  [ELEMENT.ANTI_GRAV]: {
    name: 'Anti-Grav Sand',
    key: '5',
    icon: '🎈',
    desc: 'Upward floating teal sand stream that defies gravity.',
    category: 'sand'
  },
  [ELEMENT.LASER_SAND]: {
    name: 'Laser Sand',
    key: '6',
    icon: '⚡',
    desc: 'Sand stream that emits horizontal laser beams as it falls.',
    category: 'energy'
  },
  [ELEMENT.LAVA]: {
    name: 'Lava Sand',
    key: '7',
    icon: '🔥',
    desc: 'Glowing molten sand stream.',
    category: 'hazard'
  },
  [ELEMENT.ACID]: {
    name: 'Acid Sand',
    key: '8',
    icon: '🧪',
    desc: 'Corrosive acid stream.',
    category: 'hazard'
  },
};
